config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do #Podkluchenie Perewoda
#///////////////////////////////////////////////////////////////////////////
   # Awtoruzacija
devise_for :users
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 #/////////////////////////////////////////////////////////////////////////// 
 root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root :to => 'somecontroller#index'
  get '/' =>'home#index'   # Eto nuzno wsegda! 
  
  namespace :admin do #Импорт/экспорт Excel, архивы ZIP
      resources :users, only: %i[index edit create update destroy]
  end
  
  resources :articles do  #вложенный маршрут:
    resources :tweets, only: %i[create destroy] #
    resources :comments #, except: %i[new show] # Wse marшруты нужны кроме [ new show]
       
  end #4 
  
  resources :comments, except: %i[new show] do  #вложенный маршрут:
      resources :tweets, only: %i[create destroy]
  end
    #get 'contacts' => 'contacts#new' only:[:create]
    resource :contacts, only: [:new,:create,:show], path_names: { :new => '' }
                                              #Etot code dla 'contacts' => 'contacts#new'
                                            # Chtoby "contacts#new" otkrywalsa w "contacts"

 # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   end
 # Defines the root path route ("/")
 # root "articles#index
end

app/models/article.rb
class Article < ApplicationRecord
    include Commentable # Podkluczenie "Tweet"
    include Authorship  # Podkluczenie "Autor" Awtorizacija
    
    has_one_attached :image # Foto!
    
    
    validates :title, presence: true, length: {minimum: 3} #walidacija
    validates :text, presence: true, length: {minimum: 3}
#/////////////////////////////////////////////////////////////////////////////////////////
           # podkluczil "user"
    has_many :comments, dependent: :destroy #:delete_all :destroy ---=Dla udalenija Comentarija wmeste s Article
    belongs_to :user
    
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   include ArticlesComments
   #before_action :require_authentication, except: %i[show index]# Ne zaloginenye mogut smotretь
   before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
   before_action :set_article!, only: %i[show destroy edit update]  # @article = Article.find params[:id]   "Refactoring"
   before_action :authorize_article! # Eto Podkluczenie "Awtorizacii"
   after_action :verify_authorized                                                         
 
   def index # 4: Wywod wsech zapisej!
    @pagy, @articles = pagy Article.includes(:user).order(created_at: :desc),items:3
    @articles = @articles.decorate
    #authorize @article
   end                                               # chtoby "articles" wywodilo poslednie wwerchu
  
 def show  # 3: Wywodim bazu po :ID
     load_articles_comments #Rafactoring "articles_comments.rb"
     #@article = Article.find params[:id]    :before_action :set_article! "Refactoring"
     #@comment = @article.comments.build       # Podkluchenie  "Commint"
     #@pagy, @comments = pagy @article.comments.order(created_at: :desc) #razbiw na stranicy # Podkluchenie  "Commint"
  end                             # chtoby "comments" wywodilo poslednie wwerchu
    

 def new  # 1: создать - new (отобразить форму. GET)
     @article = Article.new  # Пустым оставлять тельзя!
  end
  
 def create # 2: create (отправить форму. POST)   
     #@article = Article.new(article_params)
     @article = current_user.articles.build(article_params)# Podkluczenie "user"
     #authorize @article
     if @article.valid?
     @article.save 
     flash[:success] = t".success"   #Window Podtwerzdenija
     redirect_to @article #У нас происходит редирект на "show" поэтому представление --
                          #--"create" нам теперь не нужно, его можно удалить.
  else
     render action: 'new'  #"perenaprowlenie"
   end
 end
  
 def edit   # 5: Wozwrat i Redactirowanie
    #@article = Article.find params[:id]    :before_action :set_article! "Refactoring"
 end

 def update #6  Wnosim izmenrnie w redaktirowanie
    #@article = Article.find(params[:id])      :before_action :set_article! "Refactoring"

  if @article.update(article_params) # Obnowlaem s nowymi parametromi
     redirect_to @article
     flash[:success] = t".success" #"Article updated!" #Window Podtwerzdenija
    else
     render action: 'edit'    #"perenaprowlenie"
  end
end

def destroy # Delite publikacij
  #@article = Article.find(params[:id]) # To чto hotim udalitь  :before_action :set_article! "Refactoring"
  @article.destroy
  flash[:success] = t".success"     #Window Podtwerzdenija
  redirect_to @article  #"perenaprowlenie"
 
end

#////////////////////////////////////////////////////////////////////////////////////
 private

  def article_params
    params.require(:article).permit(:title, :text, :image)
 end

  def set_article!  # :before_action :set_article! only[show destroy edit update] "Refactoring"
    @article = Article.find(params[:id])
 end
 
  def authorize_article!   # Eto Podkluczenie "Awtorizacii"
   authorize(@article || Article)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% provide :page_title, 'Edit article' %> <!Podpis w ikonre "Kakaja stranica">


<br>
<h2><%= t'.title'%></h2>  
                  <!#5 Wozwrat i Redactirowanie>       
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>

<%= render 'shared/errors', object: @article %> <!Walidacija - papka shared/_errors>
<% if @article && @article.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<% end%>

<div class="mb-3 row">
    <div class="col-sm-2 col-form-label">   
    <%= f.label :title %>
</div>

<div class="col-sm-10">          <!Walidacija CSS --required: true, minlength:2,>
    <%= f.text_field :title, placeholder: "Title", class: "form-control"%>
</div>
</div>

<div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :text %>
    </div>

 <div class="col-sm-10">    <!Walidacija CSS  --required: true, minlength:2,>
    <%= f.text_area :text, placeholder: "Text", class: "form-control"%>
 </div>
</div>

<div class="col-sm-10">     
    <%= f.file_field :image, class: "btn btn-outline-primary btn-sm"%>
</div>
  <br>
  
  <%= f.submit t('.submit_article'), class: "btn btn-primary"%>


<% end %>

<! Все находитсья  в  " edit.html.erb">
<br>
<%= link_to "Show all articles!",articles_path, class:"btn btn-light" %> <!Prawelnaja ssylka>

app/views/articles/edit.html.erb
<%= render 'form' %>


<! Все находитсья  в  "_form.html.erb">

app/views/articles/index.html.erb
<% provide :page_title, 'Articles' %> <!Podpis w ikonre "Kakaja stranica">
<!% currently_art "Articles" %>
              
<h2 class="mb-4"><%= t'.title'%></h2>  <!# Wywod wsech zapisej!>
<p>         <!Button>
    <% if policy(:article).new?%> <! Podkluchenie Авторизация (Pundit)>
  <!%= link_to t('.new'), new_article_path,class: "btn btn-outline-primary bi bi-pencil-square" %>
  <!%= link_to t('.new'), new_article_path, class:"button2"%>   
  <%= link_to t('.new'), new_article_path, class: "button big bi bi-pencil-square"%>
    <%end%>
 <!/p>
<%= pagination @pagy %>   <!Pagy "gem pagy" razbiw na stranicy Podkluchenie>
</p>
<% @articles.each do |article| %>
     <!article class="card mt-3">
     
     <!section class="card-header">
      <h4><%= article.user.gravatar%>
      <%= article.user.username%></h4>  <!Connect "usera!!">
      <!/section>
  
  <div class="card-body">

                   <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= article.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
        <br>   <!/section> 
     <!%= link_to t('.show_article'), article_path(article),class: "btn btn-outline-primary btn-sm"%>  
         <!% if policy(article).edit?%> <! Podkluchenie Авторизация (Pundit)>
     <!%= link_to t('.edit_article'), edit_article_path(article),class: "btn btn-outline-secondary btn-sm bi bi-pencil-square"%> 
        <!%end%>
         <!% if policy(article).destroy?%> <! Podkluchenie Авторизация (Pundit)>
     <!%= link_to t('.delete_article'), article_path(article), data: {'turbo-method': :delete,'turbo-confirm': 
     'Are you sure?'}, class:"btn btn-outline-danger btn-sm bi bi-trash3-fill"%>
         <!%end%>    
       <!hr>
  
  <h5>
  <%= link_to article.title, article_path(article)%>
  </h5>
  
  <p class="my-2">
  <%= link_to image_tag(article.image, style: "width: 380px; height: auto", class: 'img-thumbnail thumb'),article_path(article)%>
  </p>
  
  <p>
  <%=  article.text%>
  </p>             
   <hr>
                     <!Ssylka na statью>
  <!p><!%= link_to "New article", new_article_path(article),class: "btn btn-primary" %> 
          
                       <! rails routes>                         <!Eto JS window "Udalit post">
  
            
     </div>
   <!/article>
<% end %>
<br>
 <%= pagination @pagy %>  <!Pagy "gem pagy" razbiw na stranicy Podkluchenie>
 <br>

app/views/articles/new.html.erb
<% provide :page_title, 'New Articles' %> <!Podpis w ikonke "Kakaja stranica">

<br>
<h2><%= t'.title'%></h2><!%= t'articles.new.title'% Leniwyj perewod>

<%= form_for :article, url: articles_path, data: {turbo:false}  do |f| %>


<%= render 'shared/errors', object: @article %> <!Walidacija - papka shared/_errors>
<% if @article && @article.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<% end%>


<div class="mb-3 row">
<div class="col-sm-2 col-form-label">  
    <%= f.label :title %>
</div>

<div class="col-sm-10">          <! Walidacija CSS ---required: true, minlength:2,>
    <%= f.text_field :title, placeholder: "Title", class: "form-control"%>
</div>
</div>

<div class="mb-3 row">
<div class="col-sm-2 col-form-label">
    <%= f.label :text %>
</div>

<div class="col-sm-10">     <! Walidacija CSS ---required: true, minlength:2,>
    <%= f.text_area :text, placeholder: "Text", class: "form-control"%>
</div>
</div>

<div class="col-sm-10">     
    <%= f.file_field :image, class: "btn btn-outline-primary btn-sm"%>
</div>
  <br>
  
  <%= f.submit t('.submit_article'), class: "btn btn-primary"%>

<%end%>

app/views/articles/show.html.erb
<% provide :page_title, 'Article has been created!!!' %> <!Podpis w ikonke "Kakaja stranica">

     <!3 Wywodim bazy po ID>
<section class="card-header">
      <h3><!%= t'.thanks'%></h3>
      <h4><%= @article.user.gravatar%>
      <%= @article.user.username%></h4>  <!Connect "usera!!">
      <h4><!%= t'.create'%></h4>
</section>
  <!h4><!%= @article.title %></h4>
              <!Podkluchenie time pod soobzheniem!>
  <time datetime="<%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
     
     <% if policy(@article).edit?%> <! Podkluchenie Авторизация (Pundit)>
   <%= link_to t('.edit_article'), edit_article_path(@article),class: "btn btn-secondary btn-sm bi bi-pencil-square"%> 
      <%end%>
      <% if policy(@article).destroy?%> <! Podkluchenie Авторизация (Pundit)>
   <%= link_to t('.delete_article'), article_path(@article), data: {'turbo-method': :delete,'turbo-confirm': 
     'Are you sure?'}, class:"btn btn-danger btn-sm bi bi-trash3-fill"%>
      <%end%>
  <hr>
 <h4><%= @article.title %></h4>
<%= image_tag @article.image, style: "width: 380px; height: auto", class: 'img-thumbnail thumb'%>
 <br>
 <p><%= @article.text %></p>
 
     <br> <!br>               <!Dobawlenie okna>
   <%= render 'tweets/commentable', commentable: @article, tweet: @tweet,  
     html_id: 'articleTweets' %>
   
<!/////////////////////////////////////////////////////////////////////////////////////////>
  <hr class="my-3">
<!h4><!%= t'.write'%></h4>

    <a class="button big  bi bi-pencil-square" href="#collapseExample" role="button" data-bs-toggle="collapse" aria-expanded="false">
                     <!Button Topic>
     <!a href="#" class="button2" tabindex="1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             <%= t('.Create Topic')%>
     </a>
                     <!Dropdown Topic>
  <ul class="collapse" id="collapseExample"  data: {'bs-toggle': 'collapse'}>
        <%= form_with model: [@article, @comment] do |f| %>

          <div class="mb-3 row">
             <div class="col-sm-2 col-form-label">
               <%= f.label :body %>
             </div>

          <div class="col-sm-10">                   <! Walidacija CSS ---required: true, minlength:2,>
               <%= f.text_area :body, class: 'form-control', required: true, minlength:2%>
             </div>
           </div>
          <div class="d-grid gap-2 col-6 mx-auto">
               <%= f.submit t('.submit_topic'), class: 'btn btn-primary' %>
          </div>
      <% end %>
  </ul>


<!/////////////////////////////////////////////////////////////////////////////////////>

<h4 class="mt-5"><%= t'.topic'%></h4>
<%= pagination @pagy %>


<br>
<% @comments.each do |comment| %>
  <article class="mb-3 card" >
      <div class="card-body">
     
                  
                   <h4> <%= comment.body %></h4>
                
        
  <section class="card-header">
  <h5><%= comment.user.gravatar%>
      <%= comment.user.username%></h5>  <!Connect "usera!!">
  
               <! Podkluchenie time pod soobzheniem!>
  <time datetime="<%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S")%>">
  <%= @article.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </time>  
  </section>
  <br>       
 
    <% if policy(comment).edit?%> <! Podkluchenie Авторизация (Pundit)>
 <%= link_to t('.edit_comment'), edit_article_comment_path(@article,comment),class: "btn btn-secondary btn-sm btn-sm bi bi-pencil-square"%> 
    <%end%>
    <% if policy(comment).destroy?%> <! Podkluchenie Авторизация (Pundit)>
 <%= link_to t('.delete_comment'), article_comment_path(@article,comment), class: 'btn btn-danger btn-sm  btn-sm bi bi-trash3-fill',
      data: {method: :delete, confirm: "Are you sure?"} %>
    <%end%>

    <br><br>      <!Dobawlenie okna>
 <%= render 'tweets/commentable', commentable: comment, tweet: @tweet,
  html_id: dom_id(comment, 'tweet_form') %>
    
    </div>
   </article>
<%end%>