config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do #Podkluchenie Perewoda
#///////////////////////////////////////////////////////////////////////////
   # Awtoruzacija
devise_for :users
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 #/////////////////////////////////////////////////////////////////////////// 
 root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root :to => 'somecontroller#index'
  get '/' =>'home#index'   # Eto nuzno wsegda! 
  
  namespace :admin do #Импорт/экспорт Excel, архивы ZIP
      resources :users, only: %i[index edit create update destroy]
  end
  
  resources :articles do  #вложенный маршрут:
    resources :tweets, only: %i[create destroy] #
    resources :comments #, except: %i[new show] # Wse marшруты нужны кроме [ new show]
       
  end #4 
  
  resources :comments, except: %i[new show] do  #вложенный маршрут:
      resources :tweets, only: %i[create destroy]
  end
    #get 'contacts' => 'contacts#new' only:[:create]
    resource :contacts, only: [:new,:create,:show], path_names: { :new => '' }
                                              #Etot code dla 'contacts' => 'contacts#new'
                                            # Chtoby "contacts#new" otkrywalsa w "contacts"

 # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   end
 # Defines the root path route ("/")
 # root "articles#index
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true, length: {minimum: 3} #walidacija
    validates :text, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    #def show
     # @contact = Contact.find(params[:id])
    #end
    
   
   def new  #создать - new (отобразить форму. GET)
        @contact = Contact.new  # Пустым оставлять тельзя!
     end
   
            
     def create  #create (отправить форму. POST)   
        @contact = Contact.new(contact_params)
     if @contact.valid?  # walidacija
        @contact.save
        #redirect_to @contact
      else
        render action: 'new' # Esli forma ne walidna to idet wozwrat na stranicu "new"
       end
     end
     
     private
   
     def contact_params
       params.require(:contact).permit(:email,:text)
     end
     
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.erb
<h1>Thanks</h1>
<h2>List of Contacts!</h2>  <!# Wywod wsech Contacts!>


<h3><%= @contact.email %></h3>

<h3><%= @contact.text %></h3>

app/views/contacts/new.html.erb
<% provide :page_title, 'Contact' %> <!Podpis w ikonke "Kakaja stranica">
<br>
<h2>Contact us</h2>

<%= form_for :contact, url: contacts_path, data: {turbo:false}  do |f| %>

<!///////////////////////////////////////////////////////////////////////////////////////>
<!%= render 'shared/errors', object: @contact %> <!Walidacija - papka shared/_errors>
<!% if @contact && @contact.errors.full_messages.any?%> <!Prowerka! Esli estj ochybka to nepropustit>
<!% end%>
<!///////////////////////////////////////////////////////////////////////////////////////>

<div class="mb-3 row">
<div class="col-sm-2 col-form-label">   
    <%= f.label :email%>
</div>

<div class="col-sm-10">                              <! Walidacija CSS>
    <%= f.text_field :email, placeholder: "Title", class: "form-control"%>
</div>
</div>

<div class="mb-3 row">
<div class="col-sm-2 col-form-label">
    <%= f.label :message %>
</div>

<div class="col-sm-10">    <! Walidacija CSS>
    <%= f.text_area :text, class: "form-control"%>
</div>
</div>

<main class="container">
  <div class="bg-body-tertiary p-5 rounded mt-3">
    <h1>Do not press hard!</h1>
    <p class="lead">If you have any wishes, you can contact us. Or maybe some advice!</p>
    <%= f.submit "Submit Article", class: "btn btn-primary btn-lg"%>
  </div>
</main>
<% end %>