config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do #Podkluchenie Perewoda
#///////////////////////////////////////////////////////////////////////////
   # Awtoruzacija
devise_for :users
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 #/////////////////////////////////////////////////////////////////////////// 
 root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root :to => 'somecontroller#index'
  get '/' =>'home#index'   # Eto nuzno wsegda! 
  
  namespace :admin do #Импорт/экспорт Excel, архивы ZIP
      resources :users, only: %i[index edit create update destroy]
  end
  
  resources :articles do  #вложенный маршрут:
    resources :tweets, only: %i[create destroy] #
    resources :comments #, except: %i[new show] # Wse marшруты нужны кроме [ new show]
       
  end #4 
  
  resources :comments, except: %i[new show] do  #вложенный маршрут:
      resources :tweets, only: %i[create destroy]
  end
    #get 'contacts' => 'contacts#new' only:[:create]
    resource :contacts, only: [:new,:create,:show], path_names: { :new => '' }
                                              #Etot code dla 'contacts' => 'contacts#new'
                                            # Chtoby "contacts#new" otkrywalsa w "contacts"

 # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   end
 # Defines the root path route ("/")
 # root "articles#index
end

app/models/user.rb
class User < ApplicationRecord
                # Ролевая модель, enum
  enum role: { basic: 0, moderator: 1, admin: 2 }, _suffix: :role
  attr_accessor :old_password, :remember_token, :admin_edit
     
  # Awtorizacija
  def guest?
    false
    end
  
  def author?(obj)
       obj.user == self
     end
  #//////////////////////////////////////////////////////////////////////////////////////////

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         #podkluczenie "rabotaet"
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
             
        
end

app/controllers/admin/users_controller.rb
module Admin #Импорт/экспорт Excel, архивы ZIP
    class UsersController < ApplicationController
      before_action :set_user!, only: %i[edit update destroy] # Podkluczenie Rolej
      before_action :authorize_user! # Eto Podkluczenie "Awtorizacii"
      after_action :verify_authorized                                                         
 
      #before_action :require_authentication
      def index
        respond_to do |format|
          format.html do
           @pagy, @user = pagy User.order(created_at: :desc)
      end
  
          format.zip { respond_with_zipped_users }
        end
      end
      
      def create
        if params[:archive].present?
          UserBulkService.call params[:archive]
          flash[:success] = 'Users imported!'
        end
  
        redirect_to admin_users_path
      end 
 
      def edit; end
      
      def update
        if @user.update user_params
          flash[:success] = 'success'
          redirect_to admin_users_path
        else
          render :edit
        end
      end
      
      def destroy
        @user.destroy
        flash[:success] = 'success'
        redirect_to admin_users_path
      end
  
      private

    def respond_with_zipped_users
      compressed_filestream = Zip::OutputStream.write_buffer do |zos|
        User.order(created_at: :desc).each do |user|
          zos.put_next_entry "user_#{user.id}.xlsx"
          zos.print render_to_string(
            layout: false, handlers: [:axlsx], formats: [:xlsx], 
            template: 'admin/users/user', locals: { user: user }
          )
        end
      end

      compressed_filestream.rewind
      send_data compressed_filestream.read, filename: 'users.zip'
    end
       def set_user!
         @user = User.find params[:id]
    end
      
      def user_params
        params.require(:user).permit(:email, :username, :password, :password_confirmation, :role
        ).merge(admin_edit: true)
      end
    
      def authorize_user!   # Eto Podkluczenie "Awtorizacii"
        authorize(@user || User)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin
    module UsersHelper
      def user_roles
        User.roles.keys.map do |role|
          #[t(role, scope: 'global.user.roles'), role]     perewod
        [role.titleize, role]
        end
      end
    end
  end
  

app/views/admin/users/_form.html.erb
<%= render 'shared/errors', object: user %>

<%= form_with model: [:admin, user] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>

    <div class="col-sm-10">
      <%= f.email_field :email, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :role %>
    </div>

    <div class="col-sm-10">
      <%= f.select :role, user_roles, {}, class: 'form-select form-select-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>

    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: 'form-control form-control-lg' %>
    </div>
  </div>

  <!% t_key = (user.new_record? ? "register" : "save") %>
  <%= f.submit 'Users.global.forms', class: 'btn btn-primary btn-lg' %>

 <!% t_key = (user.new_record? ? "register" : "save") %>
  <!%= f.submit t(t_key, scope: 'users.global.forms'), class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <th scope="row"><%= user.id %></th>
  <td><%= user.username %></td> <! Podkluczenie "username">
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= user.created_at %></td>
<td>
    <%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-secondary' %>
    <%= link_to 'Delete', admin_user_path(user), class: 'btn btn-danger',
      data: {'turbo-method': :delete, confirm: t('global.dialog.you_sure')} %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% provide :page_title, 'Admin' %> <!Podpis w ikonre "Kakaja stranica">
<!% currently_at 'menu.edit_profile' %>

<h1 class="mb-4"><%= 'Edit user!' %></h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
          <!Импорт/экспорт Excel, архивы ZIP>
<% provide :page_title, 'Admin Users' %>
<!% currently_at 'Users' %>

<h1 class="mb-4">Admin Users</h1>

<div class="btn-group mb-3">
  <%= link_to 'Download zipped XLSX', admin_users_path(format: :zip),
    class: 'btn btn-secondary' %>
</div>

<!%= pagination @pagy %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Rol</th>
      <th scope="col">Created at</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @user %> <! Wywodim polzowatelej w table>
  </tbody>
</table>
<br>
<h2 class="mb-3">Upload users from XLSX</h2>

<%= form_with url: admin_users_path do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :archive, 'Select archive' %>
    </div>

    <div class="col-sm-10">
      <%= f.file_field :archive, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Upload!', class: 'btn btn-primary' %>
<% end %>