config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do #Podkluchenie Perewoda
#///////////////////////////////////////////////////////////////////////////
   # Awtoruzacija
devise_for :users
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
 #/////////////////////////////////////////////////////////////////////////// 
 root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root :to => 'somecontroller#index'
  get '/' =>'home#index'   # Eto nuzno wsegda! 
  
  namespace :admin do #Импорт/экспорт Excel, архивы ZIP
      resources :users, only: %i[index edit create update destroy]
  end
  
  resources :articles do  #вложенный маршрут:
    resources :tweets, only: %i[create destroy] #
    resources :comments #, except: %i[new show] # Wse marшруты нужны кроме [ new show]
       
  end #4 
  
  resources :comments, except: %i[new show] do  #вложенный маршрут:
      resources :tweets, only: %i[create destroy]
  end
    #get 'contacts' => 'contacts#new' only:[:create]
    resource :contacts, only: [:new,:create,:show], path_names: { :new => '' }
                                              #Etot code dla 'contacts' => 'contacts#new'
                                            # Chtoby "contacts#new" otkrywalsa w "contacts"

 # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   end
 # Defines the root path route ("/")
 # root "articles#index
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
                     <!rails assets:precompile   --Pered zapuskom servera!>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %> <!Custom CSS>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
<body>
 <div class="container mt-3">     <!t('menu.contact')>
       
 <header class="p-1 bg-white">
   <div class="container-fluid">
     <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start navbar navbar-bg-dark">
       <ul class="nav col-13 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
         <h2 class="navbar-brand" href="#" class="text-danger">Tutorial Project</h2>
          <button class="navbar-toggler"  text-align="right" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
           <span class="navbar-toggler-icon"></span> 
             </button>
          
            <li><!%= link_to t('menu.home'), root_path, class: 'nav-link px-2 text-dark'%></li>
            <li><!%= link_to t('menu.articles'), articles_path, class: 'nav-link px-2 text-dark'%></li>
            <li><!%= link_to t('menu.contacts'), new_contacts_path, class: 'nav-link px-2 text-white'%></li>
               <!% if policy([:user]).index? %> <! Podkluchenie Авторизация (Pundit)>
            <li><!%= link_to t("menu.admin"), admin_users_path, class: 'nav-link px-2 text-white'%></li>
               <!%end%>
            </ul>        
  <!/////////////////////////////////////////////////////////////////////////////////////>          
                           <!Menu right>
    <div class="offcanvas offcanvas-end text-bg-white" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
        <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="offcanvas" aria-label="Close"></button>
         </div>
       <!/////////////////////////////////////////////////////////////////////////////////////>       
         <!ul class="nav navbar-nav navbar-right"> <!Right>
				   <ul class="nav col-12 col-lg-auto mb-2 mb-md-0 px-3  ">
           <li class="dropdown">
            <br>
            <li>
            <% if user_signed_in? %>
            Hello! <%= current_user.username %>
           <%= link_to t('menu.sign_out'), destroy_user_session_path, method: :delete, class: "btn btn-outline-primary btn-sm bi bi-door-closed-fill"%>
          <% else %>
         <%= link_to t('menu.sign_in'), new_user_session_path, class: "btn btn-outline-primary btn-sm bi bi-door-open-fill" %>
        <% end %>
      </li>
      </ul> 
		<!//////////////////////////////////////////////////////////////////////////////////////>		    
                       <!Podkluchenie Jazykow >
            <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <li class="dropdown">
            <%= link_to '#', class: 'nav-link px-4',
              data: {"bs-toggle": 'dropdown'} do %>
              <%= tag.div '', class: "flag #{I18n.locale}-flag mt-1 bi bi-globe" %>
              <%= t I18n.locale %>
            <% end %>
            
            <ul class="dropdown-menu dropdown-menu-dark">
              <% I18n.available_locales.each do |locale| %>
                <li>
                  <% if I18n.locale == locale %>
                    <%= tag.span t(locale), class: 'dropdown-item' %>
                  <% else %>
                    <%= link_to t(locale), url_for(locale: locale),
                      class: 'dropdown-item' %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul> 
     <!//////////////////////////////////////////////////////////////////////////////////////>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          
          <li class="nav-item">               <!Home>
            <a class="nav-link active" aria-current="page" href="#">
            <%= link_to t('menu.home'), root_path, class:'nav-link px-3 text-dark bi bi-house-door'%></a>
          </li>
          <li class="nav-item">                <!Menu>                   
            <a class="nav-link" href="#">
            <%= link_to t('menu.articles'), articles_path, class: 'nav-link px-3 text-dark bi bi-journals'%></a>
          </li>                                <!Contact>
           <a class="nav-link active" aria-current="page" href="#"> 
           <%= link_to t('menu.contacts'), new_contacts_path, class: 'nav-link px-3 text-dark bi bi-tencent-qq'%></a>
          </li>
          <a class="nav-link active" aria-current="page" href="#"> 
          <% if policy([:user]).index? %> <! Podkluchenie Авторизация (Pundit)>
            <%= link_to t("menu.admin"), admin_users_path, class: 'nav-link px-3 text-dark'%>
          <%end%></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="#"></a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
      <% if policy(:article).new?%> <! Podkluchenie Авторизация (Pundit)>
         <%= link_to t('.new'), new_article_path, class: "button big gray bi bi-pencil-square"%>   
      <%end%>
     </div>
      </ul>      <!Ssylki Podkluchenie>
    </nav>
   </div>
 </header>            
      

                  <!%= yield :main_menu%> <! Navi "Menu is _manu.html.erb">

<main class="container mt-3"> <! Window Podtwerzdenija>
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>     
      
      <%= yield %>
    </main>
<br>


            <!Эта строка находится в config/initializers/devise.rb
      config.navigational_formats = ['*/*', :html, :turbo_stream]  i potom wyrubaet server>
                     <p class="notice"><%= notice %></p>
                     <p class="alert"><%= alert %></p>
         
  </body>
</html>


<!  rails new app_blog --css=bootstrap 

    rails assets:precompile   --Pered zapuskom servera!
    
    gem install foreman      --- Zapusk servera -- bin/dev
       
       DLA KOREKTNOJ RABOTY FRONTA!!!!
    web: unset PORT && bin/rails server
    js:  yarn build --watch
    css: yarn build:css --watch   >